Updates to accommodate API changes in lib_xcore_math v2.1.0
xmos/fwk_voice pull request #388
Opened 2022-11-02 14:24 UTC by keithm-xmos

### Summary of Changes

#### Includes

The recommended API include is now:

`
#include "xmath/xmath.h"
`
All prior lib_xs3_math header includes were changed.

#### Renamed functions

All occurrences of `double_to_float_s32` were replaced with `f64_to_float_s32`
All occurrences of `float_to_float_s32` were replaced with `f32_to_float_s32`
The `xs3_` prefix was removed from all function calls to the older, lib_xs3_math API

#### Typedef changes

The type `fixed_s32_t` has been removed from the library.  

Types were replaced with `int32_t` where the q-format was uncertain.  
Types were replaced with the new typedefs `uq0_32`, `uq1_31`, `uq2_30`, `uq8_24` (or appropriate) where the q-format could be determined from the variable name.

2022-11-14 16:59 UTC, uvvpavel requested changes
Thanks for making this PR @keithm-xmos. Few undefined fixed point types, otherwise looks good!

2022-11-14 16:59 UTC, uvvpavel commented on modules/lib_vnr/api/features/vnr_features_state.h
> +    int32_t DWORD_ALIGNED feature_buffers[VNR_PATCH_WIDTH][VNR_MEL_FILTERS];
This should be q24

2022-11-14 16:59 UTC, uvvpavel commented on modules/lib_vnr/src/features/vnr_features_priv.h
> +void vnr_priv_add_new_slice(int32_t (*feature_buffers)[VNR_MEL_FILTERS], const uq8_24 *new_slice);
feature_buffers should be q24

2022-11-14 16:59 UTC, uvvpavel commented on examples/bare-metal/shared_src/external_deps/fetch_deps.cmake
> +    GIT_TAG        v2.1.0
I think v2.1.1 is already available. Can we use the newer one?

2022-11-14 16:59 UTC, uvvpavel commented on test/lib_vnr/vnr_unit_tests/feature_extraction/test_vnr_priv_make_slice.py
> +    output_words_per_frame = fp.MEL_FILTERS # MEL_FILTERS int32_t values. Exponent fixed to -24
This should be q24

2022-11-17 11:30 UTC, uvvpavel approved these changes
Looks good

2023-02-07 21:57 UTC, astewart-xmos approved these changes

2023-02-08 16:57 UTC, merged